version: '3'

services:
  api:
    restart: unless-stopped
    build:
      dockerfile: ./dockerfile
      context: .
    image: api-mysql:v1.0
    container_name: node-api 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm start
    depends_on:
      - db
  db:
    image: mysql:5.6
    container_name: mysql_DB
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'

  adminer:
    restart: unless-stopped
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - '8080:8080'
volumes:
  db_data:
